# Generated by Django 4.0.10 on 2023-04-23 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getguide_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusyDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
