# Generated by Django 4.0.10 on 2023-05-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getguide_account', '0003_alter_myuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='languages',
        ),
        migrations.AddField(
            model_name='myuser',
            name='languages',
            field=models.ManyToManyField(null=True, to='getguide_account.language'),
        ),
    ]
