# Generated by Django 4.0.10 on 2023-05-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getguide_account', '0005_alter_myuser_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='regions',
        ),
        migrations.AddField(
            model_name='myuser',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='getguide_account.region'),
        ),
    ]
